name: Deploy to App Store / Google Play(production track)
on:
  push:
    branches:
      - master

  workflow_dispatch:
  repository_dispatch:

jobs:
  Build-for-iOS:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache Pods
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          path: ./ios/Pods
          restore-keys: ${{ runner.os }}-pods-

      - name: Init Flutter CLI
        uses: ./.github/actions/init-flutter-cli

      - name: Build and Deploy App
        uses: ./.github/actions/deploy-ios-app
        with:
          provisioning-profile: ${{ secrets.PROVISIONING_PROFILE }}
          provisioning-profile-widgetkit: ${{ secrets.PROVISIONING_PROFILE_WIDGETKIT }}
          certificate-p12-base64: ${{ secrets.APPLE_CERTIFICATES_P12_BASE64 }}
          certificate-password: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}
          app-store-private-key-p8: ${{ secrets.APP_STORE_PRIVKEY_P8 }}
          app-store-private-key-id: ${{ secrets.APP_STORE_PRIVKEY_ID }}
          app-store-api-issuer: ${{ secrets.APP_STORE_CONNECT_API_ISSUER }}
          dotenv: ${{ secrets.DOTENV }}
          google-service-info-plist-base64: ${{ secrets.APPLE_GOOGLE_SERVICE_INFO_RELEASE_PLIST_BASE64 }}
          run-number: ${{ github.run_number }}

  Build-for-Android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Init Flutter CLI
        uses: ./.github/actions/init-flutter-cli

      - name: Build and Deploy App
        uses: ./.github/actions/deploy-android-app
        with:
          track: production
          run-number: ${{ github.run_number }}
          local-properties: ${{ secrets.ANDROID_LOCAL_PROPERTIES }}
          keystore: ${{ secrets.ANDROID_KEYSTORE }}
          dotenv: ${{ secrets.DOTENV }}
          google-services-json-base64: ${{ secrets.ANDROID_GOOGLE_SERVICES_JSON_BASE64 }}
          google-service-account-key-base64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_BASE64 }}

